name: FarmGame
main: plugin.artofluxis.project.Plugin
version: "1.0"
api-version: 1.20

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.21
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3
